name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to Abeg Help! 🎉 Please feel free to ask questions, contribute if you can, To assign this issue to yourself, kindly reply to this issue `.take`. We're here to help!"
          pr-message: "Thanks for your contribution! 🙌 We appreciate your pull request. Kindly request for a review in and Our team will review it as soon as possible. If you have any questions or need assistance, please don't hesitate to ask."
