name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome! 🎉 Please feel free to open an issue if you have questions, encounter a bug, or want to suggest an improvement. We're here to help!"
        pr-message: "Thanks for your contribution! 🙌 We appreciate your pull request. Our team will review it as soon as possible. If you have any questions or need assistance, please don't hesitate to ask."

