name: Auto Issue Labeler

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Assign 'triage' label to the issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const label = 'triage';
            const issueNumber = context.issue.number;
            const addLabelResponse = await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: [label],
            });
            console.log(`Label "${label}" added to issue #${issueNumber}.`);
