name: Auto Issue Labeler

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Assign 'triage' label to the issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/issues/:issue_number/labels
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          labels: triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
