name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and Prettier
        run: npm run lint

      - name: Check for changes
        run: git diff --exit-code

      - name: Build and test
        run: npm run build && npm test
