name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pre-commit-and-ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Check if .husky folder exists
        run: |
          if [ -d .husky ]; then
            echo ".husky folder found."
          else
            echo ".husky folder not found."
            echo "Installing Husky and setting up hooks."
            npm i husky
            npm run prepare
          fi
          echo "Running Husky pre-commit hooks."
          npm run pre-commit

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

      - name: Check for TypeScript types
        run: npm run check-types

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
